### ISSUE TITLE
シーンを Additive で読み込むと Entity が読み込めなくなることがある

### ISSUE THREAD

**Issue by monry** [umm-projects/cafu_generics#14]
## What

* Additive で読み込んだシーンに GenericDataStore が含まれると、DataStore の読み込み元が変わってしまうため、Entity の読み込みが行えなくなる

**Comment by fakestarbaby** [comment]
Single で読み込んだシーンに紐付けていた GenericDataStore が参照出来なくなるエラーが発生して、何かと思っていたら、どうやら、Single で読み込んだシーンを起動したあと、Additive で読み込んだシーン側でも GenericDataStore を利用していた（ヒエラルキーで読み込み設定していた）ため、そのタイミングで Single で読み込んだシーンに紐付けていた GenericDataStore が消えてしまっていた 💀
